# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Statistic' do

pod 'Alamofire', '~> 3.3'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'AlamofireObjectMapper', '~> 3.0'
pod 'SVProgressHUD'

end

target 'StatisticTests' do

end

target 'StatisticUITests' do

end

